# Rubocop configuration that MUST hold for every build.

AllCops:
  DisplayCopNames: true
  DisabledByDefault: true
  Exclude:
    - Rakefile
    - db/**/*
    - config/**/*
    - bin/**/*
    - spec/**/*
    - vendor/**/*
    - tmp/**/*
    - frontend/**/*

Metrics/AbcSize:
  Max: 17

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 10

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Max: 4
